name: Create Google tasks

run-name: Create Google tasks from ${{ inputs.start_date }} to ${{ inputs.end_date }}

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date in the format YYYY-MM-DD'
        required: true
        type: string
      end_date:
        description: 'End date in the format YYYY-MM-DD'
        required: true
        type: string
      create_tasks:
        description: 'Create Google tasks from Canvas assignments'
        required: true
        type: boolean

jobs:
  create-google-tasks:
    name: Create Google tasks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run script
      env:
        CANVAS_ACCESS_TOKEN: ${{ secrets.CANVAS_ACCESS_TOKEN }}
      run: |
        source venv/bin/activate
        python canvas_to_tasks.py --start-date "${{ inputs.start_date }}" --end-date "${{ inputs.end_date }}"
