name: Create Google tasks

run-name: Create Google tasks from ${{ inputs.start_date }} to ${{ inputs.end_date }}

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date in the format YYYY-MM-DD'
        required: true
        type: string
        default: '2025-04-01'
      end_date:
        description: 'End date in the format YYYY-MM-DD'
        required: true
        type: string
        default: '2025-04-01'
      create_tasks:
        description: 'Create tasks'
        required: true
        type: boolean
        default: true

jobs:
  create-google-tasks:
    name: Create Google tasks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Create client secret file
      uses: jsdaniell/create-json@1.1.2
      with:
        name: client_secret.json
        json: ${{ secrets.CLIENT_SECRET_FILE }}

    - name: Run script
      env:
        CANVAS_ACCESS_TOKEN: ${{ secrets.CANVAS_ACCESS_TOKEN }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      run: |
        source venv/bin/activate
        python canvas_to_tasks.py --start-date "${{ inputs.start_date }}" --end-date "${{ inputs.end_date }}" $([[ "${{ inputs.create_tasks }}" == "true" ]] && echo "--create-tasks")
